# Generated by Django 4.2 on 2023-06-28 11:33
# flake8: noqa
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productsapp', '0001_initial'),
        ('profileapp', '0001_initial'),
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='profileapp.profile'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='productsapp.product', verbose_name='product'),
        ),
        migrations.AddField(
            model_name='productdiscount',
            name='categories',
            field=models.ManyToManyField(blank=True, default=None, related_name='category_discounts', to='productsapp.category', verbose_name='categories'),
        ),
        migrations.AddField(
            model_name='productdiscount',
            name='products',
            field=models.ManyToManyField(blank=True, default=None, related_name='product_discounts', to='productsapp.product', verbose_name='products'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='category_products', to='productsapp.category', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='banner',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_on_banner', to='productsapp.category', verbose_name='category'),
        ),
    ]
