# Generated by Django 4.2 on 2023-06-26 16:38
# flake8: noqa
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='value')),
            ],
            options={
                'verbose_name': 'Base configuration',
                'verbose_name_plural': 'Base configurations',
            },
        ),
    ]
